# Generated by Django 3.2.5 on 2021-07-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=30)),
                ('contents', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('date_published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
