# Generated by Django 3.2.5 on 2021-07-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_agriculture_bioinformatics_environmentaltechnology_informationtechnology_remotedevelopment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bioinformatics',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='environmentaltechnology',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='informationtechnology',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='remotedevelopment',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
